server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aurora?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 751022
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    #password: 751022
    database: 0
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    rest:
      uris: es的ip:9200

  mail:
    host: smtp.163.com
    username: 15010935207@163.com
    password: Ghl970920..
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

search:
  mode: elasticsearch

upload:
  mode: minio
#  oss:
#    url: http://Bucket域名/
#    endpoint: OSS配置endpoint
#    accessKeyId: OSS配置accessKeyId
#    accessKeySecret: OSS配置accessKeySecret
#    bucketName: OSS配置bucketName
  minio:
    url: http://127.0.0.1:9000/file/
    endpoint: http://127.0.0.1:9000
    accesskey: minioadmin
    secretKey: minioadmin
    bucketName: file

website:
  #url: https://前台域名
  url: http://127.0.0.1:8085/api


qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

# 讯飞星火认知大模型配置
xf-spark:
  hostUrl: 'https://spark-api.xf-yun.com/v2.1/chat' # 2.0
  appId: '在讯飞星火认知大模型开发平台获取 https://xinghuo.xfyun.cn/sparkapi'
  apiSecret: '在讯飞星火认知大模型开发平台获取 https://xinghuo.xfyun.cn/sparkapi'
  apiKey: '在讯飞星火认知大模型开发平台获取 https://xinghuo.xfyun.cn/sparkapi'
  # 最大响应时间，单位：秒
  maxResponseTime: 30